# -*- mode: ruby -*-
# vi: set ft=ruby :

require './vagrant-provision-reboot-plugin'

Vagrant.configure(2) do |config|

  # import window7 box
  config.vm.box = "modernIE/w7-ie11"
  config.vm.hostname = "Viewinfinity"
  config.vm.provider :virtualbox do |vb|
    vb.name = "Viewinfinity"
  end  

  # Disable automatic box update checking. 
  config.vm.box_check_update = false

  # Share folder to the guest VM.
  config.vm.synced_folder "../", "/vagrant_Viewinfinity"

  
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:

	 vb.memory = "512"

  #   # Disable USB
     vb.customize ["modifyvm", :id, "--usb", "off"] 
     vb.customize ["modifyvm", :id, "--usbehci", "off"] 
	 
  end

  # use provision shell to customize vm
  config.vm.provision :shell, path: "installScript/disable-UAC.ps1"
  config.vm.provision :windows_reboot
  config.vm.provision :shell, path: "installScript/Install-JRE.ps1"
  config.vm.provision :windows_reboot
  
end
